// archive/motoko/auth_client_demo/src/auth_client_demo_assets/svelte/src/components/LoggedIn.svelte
<script>
  import { auth } from "../stores/auth";
  let principal = "";
  function handleWhoami() {
    $auth.whoamiActor?.whoami().then((p) => {
      principal = p.toString();
    });
  }
</script>

<div class="container">
  <h1>Internet Identity Client</h1>
  <h2>You are authenticated!</h2>
  <p>To see how a canister views you, click this button!</p>
  <button type="button" id="whoamiButton" class="primary" on:click={handleWhoami}>Who am I?</button>
  <input type="text" readonly id="whoami" placeholder="your Identity" bind:value={principal}/>
  <button id="logout" on:click={$auth.logout}>log out</button>
</div>

<style>
  #whoami {
    border: 1px solid #1a1a1a;
    margin-bottom: 1rem;
  }
</style>

// archive/motoko/auth_client_demo/src/auth_client_demo_assets/vue/components/LoggedIn.vue
<template>
  <div class="container">
    <h1>Internet Identity Client</h1>
    <h2>You are authenticated!</h2>
    <p>To see how a canister views you, click this button!</p>
    <button type="button" id="whoamiButton" class="primary" @click="whoamiCall">
      Who am I?
    </button>
    <input
      type="text"
      readonly
      id="whoami"
      placeholder="your Identity"
      :value="response"
    />
    <button id="logout" @click="async () => await authStore.logout()">
      log out
    </button>
  </div>
</template>

<script setup>
import { ref } from "vue";
import { useAuthStore } from "../store/auth";

const authStore = useAuthStore();
let response = ref("");

function whoamiCall() {
  authStore.whoamiActor?.whoami().then((res) => {
    response.value = res;
  });
}
</script>

<!-- Add "scoped" attribute to limit CSS to this component only -->
<style scoped>
#whoami {
  border: 1px solid #1a1a1a;
  margin-bottom: 1rem;
}
</style>
