// archive/motoko/auth_client_demo/src/auth_client_demo_assets/vue/components/LoggedOut.vue
<template>
  <div class="container">
    <h1>Internet Identity Client</h1>
    <h2>You are not authenticated</h2>
    <p>To log in, click this button!</p>
    <button type="button" id="loginButton" @click="authStore.login()">
      Log in
    </button>
  </div>
</template>

<script setup>
import { useAuthStore } from "../store/auth";

const authStore = useAuthStore();
</script>

// archive/motoko/auth_client_demo/src/auth_client_demo_assets/react/LoggedOut.jsx
import React from "react";
import { useAuth } from "./use-auth-client";

function LoggedOut() {
  const { login } = useAuth();

  return (
    <div className="container">
      <h1>Internet Identity Client</h1>
      <h2>You are not authenticated</h2>
      <p>To log in, click this button!</p>
      <button type="button" id="loginButton" onClick={login}>
        Log in
      </button>
    </div>
  );
}

export default LoggedOut;
